export const exampleWord = {
  id: '1029150',
  kanji: [
    { common: false, text: 'Ｈ', tags: [] },
    { common: false, text: 'ｈ', tags: [] },
  ],
  kana: [
    { common: true, text: 'エッチ', tags: [], appliesToKanji: ['*'] },
    { common: false, text: 'エイチ', tags: [], appliesToKanji: ['*'] },
  ],
  sense: [
    {
      partOfSpeech: ['n'],
      appliesToKanji: ['*'],
      appliesToKana: ['*'],
      related: [],
      antonym: [],
      field: [],
      dialect: [],
      misc: [],
      info: [],
      languageSource: [],
      gloss: [
        { lang: 'eng', gender: null, type: null, text: 'H' },
        { lang: 'eng', gender: null, type: null, text: 'h' },
      ],
    },
    {
      partOfSpeech: ['adj-na', 'n'],
      appliesToKanji: ['Ｈ'],
      appliesToKana: ['エッチ'],
      related: [['変態', 'へんたい・3', 3]],
      antonym: [],
      field: [],
      dialect: [],
      misc: ['uk'],
      info: ['from 変態'],
      languageSource: [],
      gloss: [
        { lang: 'eng', gender: null, type: null, text: 'indecent' },
        { lang: 'eng', gender: null, type: null, text: 'lewd' },
        { lang: 'eng', gender: null, type: null, text: 'sexy' },
        { lang: 'eng', gender: null, type: null, text: 'dirty' },
        { lang: 'eng', gender: null, type: null, text: 'obscene' },
      ],
    },
    {
      partOfSpeech: ['n', 'vs', 'vi'],
      appliesToKanji: ['Ｈ'],
      appliesToKana: ['エッチ'],
      related: [],
      antonym: [],
      field: [],
      dialect: [],
      misc: ['uk', 'col', 'euph'],
      info: [],
      languageSource: [],
      gloss: [{ lang: 'eng', gender: null, type: null, text: '(having) sex' }],
    },
    {
      partOfSpeech: ['pref'],
      appliesToKanji: ['*'],
      appliesToKana: ['*'],
      related: [['平成']],
      antonym: [],
      field: [],
      dialect: [],
      misc: ['abbr'],
      info: [],
      languageSource: [],
      gloss: [{ lang: 'eng', gender: null, type: null, text: 'nth year in the Heisei era (1989.1.8-2019.4.30)' }],
    },
    {
      partOfSpeech: ['n'],
      appliesToKanji: ['*'],
      appliesToKana: ['*'],
      related: [],
      antonym: [],
      field: [],
      dialect: [],
      misc: [],
      info: [],
      languageSource: [],
      gloss: [{ lang: 'eng', gender: null, type: null, text: 'hour' }],
    },
    {
      partOfSpeech: ['n'],
      appliesToKanji: ['Ｈ'],
      appliesToKana: ['*'],
      related: [],
      antonym: [],
      field: [],
      dialect: [],
      misc: [],
      info: [],
      languageSource: [],
      gloss: [{ lang: 'eng', gender: null, type: null, text: 'hydrogen (H)' }],
    },
    {
      partOfSpeech: ['n'],
      appliesToKanji: ['*'],
      appliesToKana: ['*'],
      related: [['ホール', 2]],
      antonym: [],
      field: ['golf'],
      dialect: [],
      misc: [],
      info: [],
      languageSource: [],
      gloss: [{ lang: 'eng', gender: null, type: null, text: 'hole' }],
    },
  ],
}
